apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:J5X0cpuFbuONcQR/x+FaxVCd/rsPyXQlS/qQl6xNLAT6QQ3c,iv:CE5B761Kg1gnZv6eGF2o0LvSWWDeSDFs7LiI2oatiCg=,tag:Z0/lanRWXBvCpnfbteRhgQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:jHeDeUZuIkQNXZxYfTimn0BS6bivqx1YsJDShgT6PiigCd8puSKpqzXm3LXBOXLFPY1mrXhms109+hSNhvM3/6uuRsj8sIceU92ahzvD3zubWD7Y8arfykYaMIUoiYZb/d40wNehWERre34tK04LdrVOY5IQhUMOSiNWBBsKGZnK17H7jYiYbgMbDQ2ZJHpQHXZ2ZiETTxG2KxG59qHQ3FAB6QV1cGgkjpene1Ksow==,iv:3QNi3g01NNS/8rNwN9j2XfFkwGG29jpu6J1df/xev+Q=,tag:UB/4j4UvkAgjpHiRPLVTJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYjJQVVZlTEVRSDFIOWpK
            dnJ1LzVmcjA3WW1lRE5SdWlES1ZUWFNWYng0CncwT2xSejMxc2E4cXo5TWJmbHpv
            VjdhZTFPckJlQTFMalRJbDFaa3VKVUEKLS0tIDlIY2VDOGdybHRhdk5SOUxlU0c2
            RXRtejVPRk45S29JTko4QVNObzkyTW8K14h9U5GlioeIZzkregaQhhVSBJUmWp4A
            30wCfzzc4nOnFDMOHhAiLqeIMZKhCpYF9LGjnsQrRTrQCdhIUyaevg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T21:02:06Z"
    mac: ENC[AES256_GCM,data:f85viMtDtI2NU+Dsj2tJREUjJ+QOX3+x5p2/J/QxpXRGfved1Q9l+1wWTTj8E8tOSsDkM3Pe1SgWxaq2JZG9TAxTa5Vc7K/8DOTaMTTQUK+ZtOczlsGWpNgy4CK6/A+pYHIxQdAQkR3HDzru8/d4Zlnpo7bbUHs0HWASgnB4CSI=,iv:w5bBSV/PTw1posS1Q23ZU47SEfFrTVE7QsgZroF0UhU=,tag:C/E2dZ5UZlcaWydBuu94Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
