apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:fkaYAXoVSfWbSfEOkDCyMywyJcv9gDXFNnN2LHgL2beFaVhO,iv:oSj/yk+f9PNCx/mmbAGWS5Ev7UNOKWN9xASsMN15Djc=,tag:mNSfFVPhPN7iFhKJeCAwjQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:p4GJk0L1U66BpH8lMm4t5h38HNdK8i1ZxH6iMrz3nhE5wh7rgj4ep47opbwRU7j7jU3IzeekUT8cJVE7bKQrRGZFMnw0VKdGsq/fUQJZNACl5TGoinm0Y2u7/bpKrL/o5ON1O/AWxiFx+ynOyRcA5YEh95JOeDyugqcFgmqqAqW9dV0AOh9KyOlAdI5kfhAailN5GAR4L29ICDgJZOnEl1PBlXW30Cqjd4JSMFUBcg==,iv:OwGkXdASUG+J9Vp0vCDMlXhRAoe4aNtiyG1PufqsObk=,tag:vRB52zj6M7qjDA7PlLh58Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUVFLTXBtdUNyT2JKQUdl
            TTNMeTBEWEhiZ0hWUk9UVkpoUTRjaHlsL21vCisrZ050S0lnK0ZlaVJNbllPa212
            T1ZPOWFCd1BBZjVheE84MTMvQVNsUTgKLS0tIE9QV0hDV0JEVjVYQ0VCNm02dzR6
            MGd6VWNWRE1BaTh0RGFoaFNUMEJ2eWsKEoufgGbX4G2hoi8BjmYT0wavbhgHr6X/
            fhkPlE7cL6HqitK4IzlJG4/WqiIVWA22O4/wMTtTYnSAIrsM8oFZAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T18:30:29Z"
    mac: ENC[AES256_GCM,data:pcJlZPDXes5NgELIOCDS9ezpVMPcl3lJJ6otyXIAILRe8D4mGtVxdVGeCRQ3ZPGj9URnKCa4VSqUl6GzIwl9axvTxal2TuJUijCbWy8Oq06fZZlj0pf/+6tC4igMZ4LJXc+od76ny+Fltk92dRKtQAAWzi9HV35kne2VOBGxDDU=,iv:WWD2/gz5QjmRf4IbgRlS6MCqYGjE/CJRjTDnnHcOtHk=,tag:6tqw1mtWa+Av5fkv/ZnhNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
