apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:3/tzeLt3g+ojfBNKXthTNo7XS/yMQ6TLy4xbl0okNfftP0Jn,iv:73j2K/snTkpMlwCWZJjBQ0NqFUWYtHG9dHdqc0bfH5E=,tag:iTRYAWw29+D8wL5nqMIGSQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:bLElD8+Xw026dR2TOhC+yZVvY3RSDRsNNifFnTU8hJ4mXklsRILX1ODBpqeG5kNfObA+QZOTXlyrOQPbRzEy9atz5oDhvFB3CvNbD3gwnnJS9Y0GuLV5LOmFNsaiC4FLhOH6cn6Nqk1ChnYCHPeTOiPjDDS23hNsFINMz9xRw8Zu36Oxfyy61NXZaHxDEYVgMCWAYyNMColTAXdNLg/aOBTQgyQF0LZ/FkBdtnv9nA==,iv:s6v2ms7kxkRqgi1rgf+z8wRCOZaJGtTJjS4Jaz2/0m4=,tag:PVQJti/3aSUcjOWcTgTMJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeXB6RDk0U0dQUFArVUtv
            SnJ3UGpCaVpxdVRUZFh0ZEQ1MWl6Q29VcGhNCmRhZXpBbmh2dXcxVTFyNnJ3U0lY
            R2pqSE84YzBkVlZzWk1hWFdtY3hPYzgKLS0tIHRCbmFoNDQyOUk3VXdTKzkvWTBD
            V0VtTCttZWVqUG9BcWdzQ1NzbzZCNm8KA1vOlKBtA022PW01opCEvV18tLfkO/Zh
            zxmAR9TRqnvog/N8XPWESda4m2eexuUTS0e3Y3hw9IOnZ+xyNZ2uUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T16:50:47Z"
    mac: ENC[AES256_GCM,data:SNYqbfRWeITRInectDhr2MdSU6Lkv7KbHMkfY925rk1XmcdbVV2g7+NOXBQP5ox+70lHIVoEH/rPVDVDEcrta7vdkKBdvhs8+zHqLO1RZxSvpddl49bkg2PiPXxPN2te1SmtZ7Zv5d4+L4cZ5GfVXh8F9HEwAT+PccU+l5S84pw=,iv:wWCXPi56BcvGN71puxBShEjYt3e9rLR1bMkgqP+4uk8=,tag:YfG9/Xdk79hFH5rgJXBocg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
