apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GfdT+8ysuO/3O+dorS5+4HT5t+YxaRxpwwrgp4Vwl3WauWq9,iv:Avybc4xRJ2M50NgqW2zBS09VZ7h/I/6q0MWOy90jOZM=,tag:ZxwB+I1rgLGZvHpQ8I1skQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:DFU+DbdsqZrpbUimGG1+pCJ5xa9EmPT+RR+3BSseFr2dylE+c970jzDBxRZc2eVGJZfcs4QHNCux7MK/aCIXxe2Jzm3349CK4Ge9CJQb/Z4VQYzNxgYYAnFSkX/ds0ewKeoPlOqVWfh8GdWYPjRVW+Yklc7HBOISMtlTogk3o9CiGXOL34qOsyv9NbDUoq174RdI02g/XSZdTqYTjb6mwsOGyYYQNwWFs2jfGCgmsA==,iv:SlnsN244Xxh0H7DxSylYTm4pN+Dul12tBW5vDsOxFrI=,tag:u/mq3PSlhPiruCZZN0aCnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWllSY3VNZ3BCOEgrZjVq
            bzVXRENuSmhOVGw2MTVNQlJ1bmdSaitqVWhnCmcxeW4yTXVqT0hqZXpQdTdidnNw
            SWY0c0s4TkNrTWFGNDBoUHh6WW1FVW8KLS0tIDhzL1p3emZ0dHVwdmNub0RLZzhW
            VkJBZ2Fib09sb3JzUFdnRzEvODhUekEKmvJfV2Xsh4kZqlS1WteuJ6b21+d97ZaI
            +xpDYR3p5FOpLu1ebmDYD6RCYaltV1w0jJWGG5wWPhWVdLw4zwnbIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T19:14:23Z"
    mac: ENC[AES256_GCM,data:pb5JuOr/jz7tqqATfOHTC9hWfvpkuaRN9zLZ08dqllaOelp0CTgHlwu56xjqSVF061NsuokFlkC/JpncDdoz6Z7ebxb5BDcbbdNWUXN8U+lw9xX2Vgctnj60Np3fQV4z6+R9gdaSfihziaxjQCHbXV9WfTAP3FuNiBNsA0jYYGc=,iv:39nXL9vYlE1I2T1VsM11faM4RRQJeTDXUqfa4cbp4yE=,tag:psIvU1kZfmXyb5680GsvaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
