apiVersion: v1
kind: Secret
metadata:
    name: sonarr
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:tfOzmYhUbOCfvymHXAalX8R4v0Robsoi/IOK+3CPEik=,iv:fIrSFbagFoG/YfmPhfzez3qPkO3aMBhK+vjaGVSJ+HQ=,tag:CTNUdcgF+ofRZREGvIUqOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQnluSTJ1R0ZYOEZlUmRk
            VEpCWmMyK0dzdTVvVHh6Yk5qWGt0UFQwaWhZCmd0OEdQcTdRMkprak1hdkxvZHIz
            M0pGRjdvZ1lkdzd0ZEdSemtlNitIalkKLS0tIFhvOW9pSXYzLzJRcWFPNHZOeERx
            a3B0d0huQVJOb1JnWVlhbUY3dGFEVVEKsIHNVBwmDSM7McG1eJ7pr42gJEf7raEV
            uFEBo4QdNgLc/0+Ke5rNOcRcHHdiefJu82UedS+HESBGWbU2MXnxdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T17:33:12Z"
    mac: ENC[AES256_GCM,data:vd9WpB5zNhlDpcWpacm6M/jF1rblB3heoEmH9wQELZ7HP/ptdLiRdKW5U1WhfwCFn0/7ge65eEOOZ2PdP0iGiyA5Ux1kWO9lHEMgcJx+8qNQNl0eLhp+Nnr4cmE/kbndgKZ+Y5gAg5qtUnyQGVfEj/HYa34JI6N13zspjup8rW4=,iv:6sE765oufBW/p6Zqcq7RDTSRb/RADYNx5rmWW8vJ3Ss=,tag:WOZ11tUHKC1XWZ7N1dzxxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
