apiVersion: v1
kind: Secret
metadata:
    name: sonarr
stringData:
    'SONARR_API_KEY:': ENC[AES256_GCM,data:lEgYCMTWCCvxToMwfxj0y8zdKmTt6cQWB+n33EVh12E=,iv:sBYs/ISenT4QU9v0YB7Z8gtwt9ianj4rLitmnnNw/6M=,tag:aUgp7iDW5AdCA/c0nb6rrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQnluSTJ1R0ZYOEZlUmRk
            VEpCWmMyK0dzdTVvVHh6Yk5qWGt0UFQwaWhZCmd0OEdQcTdRMkprak1hdkxvZHIz
            M0pGRjdvZ1lkdzd0ZEdSemtlNitIalkKLS0tIFhvOW9pSXYzLzJRcWFPNHZOeERx
            a3B0d0huQVJOb1JnWVlhbUY3dGFEVVEKsIHNVBwmDSM7McG1eJ7pr42gJEf7raEV
            uFEBo4QdNgLc/0+Ke5rNOcRcHHdiefJu82UedS+HESBGWbU2MXnxdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T17:11:13Z"
    mac: ENC[AES256_GCM,data:9lNFel41visl6nITffhrE7HlAxVbRSupCiTSD0Ex+6RhblGRJjjXIjXScyDcGN4dWyqMOvugeAf0IHWYhFMFbLcU9vp+ujhf5T1zlTTjOoXZkOZjgTpb/mEdR+UtghgSCgqd4n5zKRGWnkHcYjXCHF7bRYKK5ssWDZ7EuCV78KA=,iv:rMF2hqGavNX07EBvkoyuuEqoZymSr3DRxqKOtxvWs0A=,tag:H7jqTWSpa+FKZQtmxtdxQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
