apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3pOS/4+nFfyRR6EazspY5NG+iK0WiAvNKddiZA08LDdeKX2FKLJshw==,iv:Y4UAkEtBKk/i/Ck6BlgULyiRdY9QU8rsYSTMoT7eZuM=,tag:EFbUY/8BAHafatwqfENAaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ2F2TUxDYTJOYzhMKzdt
            RXdjeXRMZjdhczJUN1owdk54UDFsOGhFZGdvCjlpZ3NCekU3dlhnQk12T09VelV6
            Sk5lRVlhTjdXb09zaytxWWJMUTczMGMKLS0tIFVpeDF6UzV4bEFSYVBXbTRveHFB
            c0lHN0FoQStCNlVHT0lac3A3M2tNSG8K7BZ0n/Wu96c9FM+x1KG/yDxoks5hPt+J
            HhDTv0KAvFN0laEhniC1dHIvhpRQs9y7LfmgsYinHVXXKEfoZkuriQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T16:50:47Z"
    mac: ENC[AES256_GCM,data:i5MMjDVEdVHUTweITGG14HwRjxSKUW+ZocKFgjhjrB/Ya3KX2/Dp6UaPNgmp3RSRdv4BDGipoY0M25veqPRkoyRWeRT2C9OFk0UAkVY24nvitQB/y5bgoHP4Xynh0mmhNdyEY9vUsHH0cGCyQ7ZsIHQR43X/Lk7ax/f6l1eaA9E=,iv:/nvmZXDiZP9tImuYh8+eUIITrQoeUTLPX8pgjiLLi0A=,tag:BK1WO5hwgOUe6nYuiLkYww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
