apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:li7TtOAhuHADAVZAHJsVTPkYUh1iUzlJuUaa3csG97o5n+5DVUyxqg==,iv:mQs1ioeYt6wV0pVTTmPUpRnG/KJyf4PeM2DXAnwvo1k=,tag:Wm3/b9zKnSVMeuPkCRrgjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMmpBV3hoWEFXR0laNVF3
            ZWtoVSt5WHpnNU9Yc2tDSkRCME1scFc5VTIwCnlMMXlKMTRuOGxUOTJ0YlhmRm02
            Q0xMQWp2Y1Z5ZmpFa21oUzlJN3dFaVkKLS0tIGdMc1d6b3Q2MjhzcW1JTUx5U3Yw
            WmlEU1JDTk83Wmd0VlFKUTdhVjhLbXcK4pHQ1kvRuy75zZI6PtJ2hSE5Z1FSe2/9
            wQc7iSg8HX301d5SdpI6TKP5HUZE95iTzM6kPWpN11SklLOmjgBZ+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T16:43:47Z"
    mac: ENC[AES256_GCM,data:xdedUB/QAaux+yyCllqNtPjT0aYwnGn0n1GAH9a6KMGHOc/YOMYEhEg4+zEdEQOzvgtU46Mz9SUMPtH0EFvGSMQineDpQXYwiBfAkxAuqcpfBALZNWZiuJh0GZg1BjYhU/dSjv6m42kpnQt3m/Ulr13pvzrMpxY2BC9Bsm9gR9M=,iv:L55jWQ+sD83KU0n6Lj+LlwzDkRLQ+wDoYUsZFzXVD40=,tag:l8OkSYOvMWtYN1gw61Hgzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
