apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Q4Tqz+8nDW85FfoYQcmZl/PbQLExX1/4KC2xpIpPBhxcYi4Lp3S/rA==,iv:wRtyFtEjihKl7BwFZ+4YW6+o76UfmNK7TRp008nQens=,tag:lmejw/3+yA+E4kg/CTWLIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUWhOZnZQbk93OHdsYWZB
            amp3SkFnYjNzM3JMWFJyZWNlWndNYmhXTm1VCnNZVXN2aUdORGdEcktvcTdJNi9u
            Y3ZSQS8xbEpENk9hQVN2a0pMbEYzMFUKLS0tIHNHbXpPNUFnaC9zMWxzT000ck9J
            RnhDR0d3NjRkSmJ0V2ZYdmNpaFNQY00K75oWGq10gacOp4WfyQ76206I/nLZzb4H
            /N84m2Je8cfc6Q+81BTp/9dSYV9b4SS5o3ZWwSHdmelYDWr4K3wDag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T17:58:14Z"
    mac: ENC[AES256_GCM,data:C/Qoadhk1Lsreqhg9vZEtIB3jgyf+HSxieDzyspIGVYXu5DZVeBg4uJQ6EzqpmerMmrle8GW8r4U2CbHj6ddS51nV0AuD3IEJR93feWEgZk/hfoojG406QvUgGmS4lGEyjVADadGW5CfVkdLeC5C/QHiOiyVtAMcefjzOHYBPms=,iv:yb8HfVba/ZEfMN7ZSOpBDgFkHGb4vgzk8syH1epWs44=,tag:ZoJZ0F9jG7LJlDw6DJIueQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
