apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:czLuN36MfWApAbQjvIWOY2QFv0/wXb1inMLKZBJb3Z3oZZ2BGA76mA==,iv:m0iGf555FzCwjnyN/hVdtRoV9Z/83ExyhqagMpzrMBM=,tag:ynvPcUOMFOp/DBHTVlAdKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWDJHNFo2eE9pN2ZWci9j
            enJBNGk3S3lCekxGenFYSUtHdHVkaWFvNTFFCmNDQVU5UFN5R2JPZnNkU1ROdE1x
            VlJWL0NSemhQOW1XVTBzMHhtRHBOLzgKLS0tIHhEcFlYZThXYlcyRWNxOE9zQTRt
            cVB1Ry81WDMrVXluSVB6eEI1ekpDVk0Kd0yEPfMozSi4YeCUKRCXx551Jfps/lEk
            23wAoTM6vEFqYXVaAHIxffdZSHzBmRk0TRjp42cdicBw7nZPlNG8pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T12:09:52Z"
    mac: ENC[AES256_GCM,data:henT5NVczP2Q7VrzDLSLG9bcS3gjnNaS2LyBo9koVIE+Tn7N7kRI5Ua1kTrpfJh0S6siiuC0kXr6/RgS3wI0hNuaYL4RJ1Tlf+pt+mdf8b11NXot7qYySX4peWeBTn/qY597tmS/6vwkLhJPxPJghkzcCuLkNZS7N8g496QL+Es=,iv:ojui6EBsWfEmmSio2MfPqgWZbpDPBjDtIxOyn+I+CQA=,tag:x0uP7dGuduqQx4cLt911Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
