apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZWXfR3ev7fnHXSy9DsRCVwcAVn0/OxvOjFloDe830xj9+yKFr++BHg==,iv:MNlcSaegfGj73d67xf8Pqueiub3btvRZXHyZYXNUvyI=,tag:RgMuMJdxYQytRagL0LmgSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqS05SSXNKMzJRZTV0RXdM
            aWRDdGZaa1JSMlh6MUtNTVRRejZOWjZQcnc4CmM4M3krdFZvQ3N1RkNlRzNvSG5T
            c3pzTzcra2dlSlk1WEFHcVVJOTlaSFUKLS0tIG9EdWFEWWpBREM4TGVxdExjYWtq
            ZDF1Wk9uc2h6YlZuVldUU2xUY29jeWsKk39xEYdgoyA+PgnOaax424o8nxaMq98t
            mC+m/9EGDg85UOpeihzDSS8569kAlscyyHjJy6cdak5D4Z54kFc8kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T15:41:39Z"
    mac: ENC[AES256_GCM,data:VeOBVvOKGZ4E+uXsUCqtbwWCjm7erMAyZTnb33yE8N7CJ2SukPSzZwf/aAJoMaXAHpOt3osvHkvMmvSpFJS3qv7hqnxyDZxKpJQeqS1QDEoxUvE8/DA7ZIhkVOn9Olqikohobo7djk3bIBXJ3zsH4JDR0mSUwQ86uDKwh8r4aZY=,iv:8MP38EEnm3pssAflBpYBwDCZjjY0W5dFvingUN/fQe4=,tag:Ch7qB8yVcmtSmAyNCxbsIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
