apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:k31Bt3dzoTpRLvKhK9PKapCbZpk8pEaHC68UInFqtkzOU51kmT56yg==,iv:N33fLD+U8aRdjOvyjyLAYXs4BZFuZONNkw2oAlq/ZoQ=,tag:HIHVQYxvYvx/ezwkN181Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYWtITkJNWXdpb1pHb2Jl
            NUhYWGMwSkZoUGl4cmZtQW13NXdJUy9nY2xBCkw1UExTYlQyaW5oR0ZwcGlKSVBT
            TzF5Wk54VUZjWStnWlZwSDg2aE9yUUUKLS0tIFlLUWxYWlEzWGQxVFJ3QmxKV0tO
            MHdtdzVoZUhWMS8zMk5PZFQ1MG1vNjAKoJ8PlGkb8sLThCFJxyTAxBveTa+TkWMl
            nmZWgkYIoP2i5Qhi+dB//4SAdl4wwmNDhKrtvTByh53ykgH+7LuWAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T22:28:37Z"
    mac: ENC[AES256_GCM,data:TleWuIBIMpZ5LTFZHRg/mNhEdPTTEgWsyxIkg2SGSVq5pXLEyFUVysy5WRUR/llbP9RabiYeuaAmDTDm38mF9Mu/m+GVmJT/ExDgXjPJcTAz5WUYaAz2XS+950pbP+O6X2P2sZSFIL3j0ROCF14b+sYbncBJPBC5wJJJqiGIlBM=,iv:hdcxTfSszCD8J4zwVuFUMP7hjZNVbGuHDLiPI6V3zSI=,tag:O0QpmZU6YXjHtAj4gUcBEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
