apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:YmMV5QaZI62TQB2KT5dy6XiRqnM9poFN61ONa5ooj4l4Lp1YNG1Iig==,iv:k6Nmv/BusnLLV7yeSDIQ/SiG3UDu/+E6wKWcTkekpLY=,tag:iksMUgN9ADt1gOhWzwfjIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWlBQNFhoUWJ2aXIxcTh6
            Q1lWV3Bvd1BkMUQyL2lSa2VzYkpwYThiNWpzCk4xY3Z4MzloZDN5cmQ1aTJqUEdu
            MFp3OXptck9pQXNueG0yYTNENWJQem8KLS0tIHBka1NDVzdnZjRVcWNjMG4rZmla
            b3U3dldtald3bDl1RFRJanNSeGxtVWcK/4ViZYC7RoZgnB1/pY1eIKSjQd1W5Qcw
            /CoQnIxonvt1y0byeJCkGcaAg4kWCmeyL74O+scRI2+X3WbO15jhXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T21:43:59Z"
    mac: ENC[AES256_GCM,data:x3OV2ALVlCvKxIGv4Chd4misFNBnNMYiajswi3U4ZNG6QhMWZ9cAmExBbL2TAmDS061W9eCvUYWuToq4DNpsDBq3Vfb60soZ84ys0abVsUtyeqSgeAO50BeXnfT56xqM/FALz2PAIAOoqC0I6I7A36vIxeOBSbMDIu2mxqgqOGs=,iv:E+76Kze4GTvUDnckKCrG4giPUKhADd7zJ/gJuygylEk=,tag:y+5eQF2rO4EvObcN+ldKHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
