apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:+Hs05wklGeaGdpxt9rwPYlwZJWN+9GCTLb89LhulMWpNKlqFFN5n9Q==,iv:+qzBj25dMuBWzlafASivNFJ6+Ww+0DcgtiBXOO3K11A=,tag:JCzpVb+Kd/s2feL6lGcs2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbkFMRWx1ZXRLQ3dYc2s2
            eHlPYk9XVGVEdGt3dEpSdWlOZFVoV1JVcVU0ClJFcE1zK05EN3krTWg5eXl6Mlgy
            QW9YV1c3ZGVwcXFDMStIa0RZT3pOaWMKLS0tIEs0clNVUTVGcTAxQzJDWE00NGFq
            R3ptYVU5dkRvbGlyMVRSaytrVnU0SEEKfLpP0jBGDFyd+zRZeXVzgSd2zsYsBEIH
            vLJOaBf/KawTqxj1Xp3zDlzKCBZ7eTBvVNbaQ8WKT1diD51hSmK/9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T21:39:20Z"
    mac: ENC[AES256_GCM,data:r7b7K+pQEU5LSicF7zhsFelpp3s4EWscR2yR4f38YflqXeldQzjog+4B3umeJyYB+IoMQFlJbN+5KIMG5QZfI46r9uA2n55yCe6Ewr2Y4n+Awr1emvZDXn1xFIKSGNQqDnep99RVFiCZL1j6jyJf+CxWIh1cTaS+tajHft81dR0=,iv:sMB7A/9vEP/2NDYoZpsdM+la5f2G6Af8S9cUDGSoADc=,tag:yw43FvsofWCaxkMBbrmWrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
