apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:dwWLarfTPOW0R3paVrXpZAqv11XU7lM9ckOqjr7Ys5F6tnu4Q9GbaQ==,iv:D+xCx3c3Glijd6ufpqi5hOcblsVcCLvtQFM5erBKeFg=,tag:bwKLy0qKgTxKbdow3V3XGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM3dNZHFqd2NrOUFxTkNn
            cGNweE0wSFRrODJDbmRJNXNaaVpOVkEzWFRVCkh4SzZPei94TW9RWXBFSitIM3g2
            c1dwTUZpazFZT2RBOHUwTkdXM1diRkUKLS0tIEZGWkpCdmlzZkt4U2NrbE11b1VY
            SXorVVY3NlpFckZERmJ4SkRRaE5YbFUKNDGb65DSTSaQXEUTHb7ER0M6/Zqdq0He
            HNfMFyl4P6xSk3Lo0cc8KLURPUTbE/OXQ4HVDoFhYi+hM711KYzZuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T19:03:20Z"
    mac: ENC[AES256_GCM,data:6Bc8unUQnBfZtbc4WiyEddSfqnqZOdCCHZovGY9OMUZmgu0ySd8r2qVfQL3zyxnJwq7O6sKCN4S0nF5i/vth9Bde5cZ8TH1TYy1xD7udKlhy3EdMFmfAgNs+Q2LvKF7MiOHRyPApGHigkOc9G72/gn5z7Cqu9w7JmmeX/gJrkOk=,iv:uWm41y4F6PLYCsUyAOpM1hpH8mJDHwH1QK/tooXoA/M=,tag:4Wblht2vHNPD1FeLRmVivg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
