apiVersion: v1
kind: Secret
metadata:
    name: radarr
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:V/Es1iEd+MvS1SFFq/hSIjJ79U1VoPxm4/9697SzQ3g=,iv:PH1+Eo6HsrNBoA7MJGcfhXGBsLt7AIpPR6oXExYSyWg=,tag:1i61ys4vkL3T4xAg+qffQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZEkvbUUxNXZ1OFAxcVBU
            S0ttU0NnQ2pJU0ViMnFORjZ3eWtYMDRyTzJzClhuQ1JPSTRzaURTTTdGM0VRbk9m
            dzB4NWd0Q2dLTElUY1AzdjRRK1YvbmMKLS0tIGZWaDdQSnEwMUhQdmxQdllVUVph
            eUhXOUpUb25hVEVuY2RkVDlMYkh2U2cKc3ZiTbOzMDllQU0Cau0Y6kGiHkwnYxqn
            JANu1XI41nwUoRk8gYwbZkn5fM/uy1KNuzUaBOUpo+LvQeMlv3yoSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-28T20:26:42Z"
    mac: ENC[AES256_GCM,data:5G/tU0MK7Wcnb6l5b/8Ed5dxfu16VoRH/Nq10GyoGnII8kDYdGJ9+xQTjKk3qaQ1T9exGqR1GuVe2ewyMIo5v/qyRZLJa1G1G4BNfoHKrONnnSZzRCl8K5C3nlfyM8mPWQXJtzHCz9w4gCrgx4lVfnmAFmO0fyOKVF3OkSSCqDU=,iv:9S62JHIJpaGK7y8aw9Tvqzic+qvE54SP6bLhaQeLv0g=,tag:xtXuNZFO38q5LAL9NRp0zQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
