apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:XDSdsaqUx4Siq/w=,iv:7Re5q1jIKCKqW8JQhkvb5huReQt0JN5ixPfZfUp1xPk=,tag:ONQgLmtJSluY4MuY3QRGYQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mE7NN9sJ6mHMk7UelN2DYcJDUcc=,iv:W0KH5w+4z8/yDToAlFV8gpivOrgeQxs6+J3jiuMsZmE=,tag:/6QO0OCv/RBTwVHPTUwG+Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQME9FeXorUVh0QXgvdHBN
            dW44b01CUHYzK1dpNERpV2g5dDMzYW82dVVzCkRsY3MzSGVOWGpNZ3E4WjZLSTBw
            cXo2ZTNSaytieGJPSXF4WllxclJncmMKLS0tIDlSNkhVNXZkSHBDSWYzKysxZmZm
            VWNCRkI2WHJKU1JrMUFabllZMGpDMXMKJL7h6FJkuhdjk2kix2fFSPYXk4Pnt5lq
            lkUZ3y6WllREYy2SCdrxeUIMPOrxdCp6j+n8KyVj4SImadk3QnLuWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T17:13:08Z"
    mac: ENC[AES256_GCM,data:y+nGmdy2DeImigdggKYHRzUUaIHT8N/bWBvAtwOdD+ieQRILij1p4o4QdQAH8D2GKsGl+p7L3V+dT2Zo//2o1RSwgBVYhP5X0P0NsovAZ4V7EosWTrzzt3o2MHtjq3/HBm380ebb/uv28CqbqP0CgW+tudzpzKQyo4hVWPIqXZg=,iv:rT3DmwuDXKsMniC87kKr2y7XOCxsyvsutwLacUC4Fuo=,tag:y7UYf3UhDc2NQXt3PNigCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
