apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9q/F9yQS0rmNCw==,iv:F9vAkXpvw2bO/qpbDGjw9IVmSuNLr58VoOkDD0qQXoM=,tag:qUHJEeCBSefxUpKIdxDT/Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:H54i2/q84pekKfA2F2DGnx0wXyY=,iv:3d37Ky20MoyhznrsS+4TR3PxUqxef/O9ZvIuu/Bf2iE=,tag:svBhtBvWdTdUooHd4TAPcw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:QdEWgQ7N1+2TsynRX2WWFpdaHjZHgxiWyxrV7BwPficlNCI2,iv:r7yFt4Xqeu/+9TQZ+LFWQEAxhyGDxdtAoFkfYlsVJVA=,tag:ugrofQ4wL6FWA1e7ae/BaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U3M5a2doOUJYSGlZZXhr
            YzRxUXkwYWFxU0Y1dHlFajBDZENrTGd4OEJ3Ci9CV3lWR0VFU3J2QVRKUFBwSG01
            UU02NkZad0tDSkl5Rkd5WlFJTHlLQ3MKLS0tIGFYQ0Y3akxPTjBTUndLbzhma3Nx
            Z2tqUDlmbEFldktzOWZ0MHdML0RFd1UK/R548P9ilvfwsLJ1gr94Nc9uUwUGTr0D
            /y72Vu/4c8Ri+/7KrvBCOeLboFKJlXHkx921QwG5KWHuA7vQJinytw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T13:22:00Z"
    mac: ENC[AES256_GCM,data:IVUNMunTDX9dI4N2EkV2j7z2qMn5bKYAsqb+8CvxaQg+ah8AFHsNEiBzAPSRS1qpVUN/v2Cf4q7UY6Oi5SxJRRY4H3aOQPDMClpC1GKhwFdmpX4C9PclHwDDsbPlDdVpoiqDc/+hmZBpSgRsDBkQyX8LIkCHSaqQOxdtPHR5CzY=,iv:t3sNm3rDbnAnprg9QFP7YwdxMZBXg1Rhws7pj/9M+oM=,tag:MCrVOaRX1UTYbAXW42DJ/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
