apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bnAIo6vwz1nbQQ==,iv:xsDYZS/uxoa9oWuKkTH1RAIu7YZkiV+HR3Rx0yCjBuY=,tag:8hagoGu8VTQYvadiyKJWjQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:gebuDSrNq6F/7kEHIS7NvHeEXSA=,iv:hYJT74/B/711i+RMDmGaGyhS3rwUXaaebCe1/LBGlEM=,tag:VsjseA7BWKI+2ck0TqvWYA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:XISIuEeyiOn098cNHJ65uGHRr0lso50DeVw/HnooA0zOQAPB,iv:Uh1rnpGe+R4L19E6WdmtQ+SgHmzl7lk9prHkq3ceq9M=,tag:cRu4xZpSViQ9tJFnUasmRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYTM3a2h0d1VvaVRNVkdw
            T1NGc042RHNFd0h4MGpMenFCbytXNndwNGtVCi82ckdBNG4yYVRNcDdCOUJsbmFB
            NitJc0xJMTQvSDNib040NVdoWlZ4ckEKLS0tIDFGZFNITHdZZi9wVHNaS1RDZFJz
            am1wZW9hRDRhOWVnTXFUandjZTZ2YUEKXj8h7XB8dx+6IXoK8ll7T2eCS8I6F2Kj
            jvc5ByjRYy2kpPiJUSdi6Sz6iGAyMNKMPnDspsX/9TVAKtbhzDj++g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T10:38:45Z"
    mac: ENC[AES256_GCM,data:ydp4r9DF5bJeJ0Nm9m9UmzQyJvcu71IObMWEjSR9QKs0tEj+wE+HBdruoBA19FOgA3i1J21XZLeExuPy9J9mhPIeXaZ4f49nz+JDp1tJi+YCyzYMqa4CXool4HVHmYCaD2ucCy9m8MCzj2fT/FGwraDYjH1TFV+xFwzLXnYBFGY=,iv:C6b4B0YEyFvZE6FE2ywT1GLB0306qHPLhclHYFr7WyU=,tag:bc0APzGJNAjaiCrHz7VM+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
