apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Wh5p//giMOhc/WA=,iv:6mI+v4eEors59VPWp44FbzXDdM+fbnyTGiqcoyIuWys=,tag:0WXryFZ2xgRw024RgyHarw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:G5hP8jz2ozvA6g0Co+l16PMCPPA=,iv:sFZI0m/ZbWnHrh1Taj4f9QyjjKTN8c7EbhzlJ/1/B+w=,tag:fgc5EqfGemfYMhPuac/OmA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcmZmUzlPR1FqVVo4WVV4
            VENUUGRJSXdIcUhTejB6NklMTWE5OWMrMXpNCjZqTEI2Nlc2VlVNeW14WktGbjZX
            YkV2R2pHbHF1a2pONkJsaVpabDJrL3MKLS0tIFUxdmU4UHNjSm5RbkQ2blloMWNa
            V3dEQUUwdDVlM0h3Rzg5U25tdnpSNlkK/oFlIxlrkfQHXAy3iSJrsGypIggR+Haw
            28vPs80JwU08uoiwy6JjDru6qi87zCSSBW5IBW4zELgDgZv8DSHW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T19:03:20Z"
    mac: ENC[AES256_GCM,data:lm75xA9rE+q+veooUJNEjgDJ6ZE6gtaaX2sdTTNEzCmJL+xitX1yuRVMkTfsb+Gk3Ye1f39my+FhtOKSpfb3xo3rGjrBi3i1Jv6xqdOlOrERyPtOw6Dikrh+TaccEmhWL9emscnq3bWx0aC6gAAkGWkbaBAAHYEPeO4NU3g/JXU=,iv:DtwrZSkDo3fVGnnkn6vjUYLgozEvVi14oDfFqPOARpc=,tag:1BxTNqxM+wpvQHGMJJOC4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
