apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:qfL0+1fs9UzERCgFb4IKGJYvw6mlr5E0kDev2SWuEME=,iv:jec4eJikJzi1bGX/uI6JdQz+otGfh8OM0N+xHWoDtnQ=,tag:Hp3eeItA0jx22gQnVOqqKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZXFRRmh4end2OU0vZGM1
            ZFV2dkYwK0d3THR2V2JhWW16UkxLYm9RTlFJCnprS1BjM1VSWDZ0UFhDU1ZvV3hp
            NU5kbGQ0NWswcWRSM0Robk8ycDhOZXcKLS0tIDVyREhESkRMVkR4YUFXeHI3dlRT
            Y2c2YTRwem1LRFZsRHVlMUgvcGQ0eWMKsKq8VRgX3wcF+jVEeuJ9nEl2ggy2FefM
            bYk5Ya1o5jU6vSO+724a9nXWb/MA6IFghFMInoTgMseZu49Os9ffWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T21:21:27Z"
    mac: ENC[AES256_GCM,data:6ur92UXdIlUxXR/OxMSHLTa0IWur5zXT4X0Gn6gNxYz0tAFUyAD5y55RiAkXvHlo5Cuv/2CGswz9x4ZFiAJHk4Uk6q7DEJkEQj4PBBv0Repo55WXNt8JVaLTEFHe9wYtx2XNn3bq2IzrZr1AAVzlWwlClvhAiMf2WqRFYT6qfqo=,iv:VCxgapeNO649TV8a6dj+pq+PQn1T99bupmnOLT8Gp2k=,tag:HHKoPaBZ1abnXFnvCvqOmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
