apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:e7SU5/iPeR9jj9EabUG9XXZF96F/a4leaY3qm51/YsQ=,iv:L1zLJLX+6qKTwFQYZZ5vCmRYf5H7aqAsFbjLg2srAN4=,tag:bY3RS17rnuOOb3U9Zgomrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMC8vMDhjNG9nUDZRZk5l
            VTBDbGdpUWVEekQ4WXhGVW9sbU9nWkxkdjFZCjVTTG5aOTJNOHpOQVBiaGQzOGcr
            WEhFbHc4T3pCbUh5OENEVXE0ME5IWlkKLS0tIDV2Q2VDOTZIeU1mNTh1Z0h5cUJl
            Q2h6MC9yY2sxZnJNejFydm1uMXAzMFkKHOlF3hKUMi0Rqrw8kGnJrQpdrgGhnQoy
            mdAybxizjL0jZv67xaSNVcD9oG+6NAJ0uisljAldhFsJOgd0txu62Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T19:22:41Z"
    mac: ENC[AES256_GCM,data:AZ4aNgQZ1Iz2z9vk2EHI0N546NrULYqv128WJhUPUeFnMJDoPQV4zpd7w8TndCKb62SU1zzO+v9elpj5x7ycUGuR4Ly1Qtfi2uk9Se+orPBkFMSjlbI3iCe+eX9m8CsX9+4w4KCv6hJE6hByM+B7uBNcDpZoFWE74IaQHBko95U=,iv:2+9YBQxKwFC20pJsATTGCqWlbSs563qI0lyVrvFb8As=,tag:dLlzwe8Y93Zpl9TXIzR/AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
