apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:K9RCTOe/WpWnCRilAbIHOEo5GYdn6U8Oax9AyxSd9Ig=,iv:LgPC+RjtgzfBDLOEsKbe8z8i8qrk+7H16/BKM5Z4D2c=,tag:kp/OSGxM/zTjiXAzI4Lmww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QkpLVk9Td1hzbGlaOExo
            V1czVWV1SDlGelA5anBwRUYzeElOUEU0ZkdrCkkvQ0tSN21TR2VCdytUSkVBQnl4
            cVUybG1Da0NWcDdGbmpZdXRXOXdiMncKLS0tIFU2blZ1Vm1rZ0Y2WU9NZzBNbG5X
            MW9rc0tTL09WcjNBV3hUSkRvbnVRanMKuDwGiKVfSrvVnoxNi/vodgMJsoYneb9M
            BsL6FoGvLhYBLeyr182NE8Ob4irwrTXUutsEYb32yLhWrMUxqpep5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T16:50:47Z"
    mac: ENC[AES256_GCM,data:uRDCqpyQBeMClIbZRY5bXwU0jHV7qbpzBLWAyAzCYEWuwwws6BNU3oRjkQGrBSvXgxgSfXPwg+04alHOEZaSU2JKvgqPcURfvA6VAlaqdGTbvkwqUIRJtWFwk+vutiolKEPrrd7mnw1DdslK7b+nuX7DZTCwVvkUI0qOMhfB2lY=,iv:B/i2OXEOqOBc1n0ezWRmonPLXKPd+Dkf3pbbFNqY8kk=,tag:WOWu8djLV9buYliI+BbSWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
