apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:8Ff3WocmxN33xXBXqPszvoSftxpGNv5OvCHA6aDq8fM=,iv:qzTRF3BmSVoxrTldUBQgHRNFttpZ9GPydtUI9jqtgkM=,tag:pf089+tqrphg1PCNl2xqFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVDQwdml6Q0t0QjdOM2xw
            cUZ4VmhoN2N4MFlKa2huaC91UjNRbGhqVTBJClZBNGJTckNhZFZpS0hLbndPMkk3
            aHNxTmpsUUFkM1ZQUkd4bFRneFdJVDQKLS0tIEhiUHNwcGtpNkcyeWQrWUtsSTlT
            MjhTUTlTVkhKdDVmTlNOWnRJZXA2S2sKm64EXgNq9XH70rxJMgXsdYdKlAcwebXf
            WF0Mi/Bf40X9qUhWJ9IWYDmNlADQb0zlfI27dRe7GtWYhPOM450eoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-30T10:57:06Z"
    mac: ENC[AES256_GCM,data:BvvmAktcX3fQKwQ3nZ3zPPQuivbwyAnZQBhPEv29AIuw94o/ILwxc1DLAAIs9IUlQd6tC5Nroc+wJtp1UY2tXzIzKVBmcHapRwbGnB9jnyyxIsUSnYN6efdzq6K6kej8xHURNQOQptCRRzAr4FJqJaFcpAfFEeylRxiO6KelgFk=,iv:s5GIvjlBUV1egJyl2SWyv027muLD7gfc8knpfyIBxiQ=,tag:2PCj6cP9e5A1JE9njZKFyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
