apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:vw9rTTm/Rm6zDt/sA73EC8HzJB0NPi2Qw7JEVP2CjLY=,iv:UxNJMhQdvm7gjGKsUXREtXXbY7Zfq0zngw+kxB8q32w=,tag:nzDhWEPKyHJ09e/IC0QxvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SHB5N0JORDhETlkvN1JX
            TDlkSFJIdjA1OWI0c3VzZEhadWZGY0d0ZUdJCjFPcENHMWhQUXluRThkQlV3LzlK
            UDBwZmRYWFNoYmtqY25aMHFLN3BhQk0KLS0tIHoxWnVFVDQvaE9NTEZLVTd1L2V0
            NzFibHFtalRYTlJZKzRobStHcTBEdWcKqMrAf7D+U58tacNOmf/+bl0yG8P0lZkF
            waCpYR+MH7IFl/NahDdYKzZGiZP1Wb3NEzhtkwT0WZv7O55cNmu2yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T19:14:23Z"
    mac: ENC[AES256_GCM,data:kwfxd2xb8/xjF+pYWMx1NRZtXcDNouxcVSRheE2V9Exxc9TuHD/iVoHQjeHLppeXsI/IsJUAbRTl8PfIzowC5VT15wrd9NtR/VuMqcQLM0+xT6NZ17PRrHsvjb1g5+EQXJJSe0MfmwFNaLzHd+7v1EonUCTVzqbSOaKeNm890TM=,iv:U3uJstn6rX4hn/A9AfdNQFlJ+Im8bRLBmxpsxdxWDt8=,tag:RWCihsjtdtW5AKpo11kLCA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
