apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:VrMZMvUvmfKs1+MBD7m+8Wg86sweYZKbM4ahgHy4KXk=,iv:9ixb1kz6wGWsvZaDXO/L+rNGSx4Ze+NI7hHrSnncKqM=,tag:rM9IUD7SX59tyahXCGlxoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUU8xRFg1S1lTdUNFS09T
            ZG1LeXRGK2dOb1FDN3lLVkJFZXpEMHlva1RNCkZVVmlxenRQWHJGTWVWTGtuMCs4
            cFl3OWtyVC9ENTZob09sUy8zMFVPdkEKLS0tIDh2ZG95SE55NnVFbjhzTjZiNnAz
            WmdCc0FibW9oZ25vbFJjcHpIcmcwN00KEsQ0LTGRDQRsmcwYxvxtI1/+ytmrxZPA
            Bjc7xtwiQfOIWoiNz4gb3ca2ymihZaierBuwsihJcJnp9zsKH1uEkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T15:41:39Z"
    mac: ENC[AES256_GCM,data:HTH8TRdqSQtmqA9o+YVCdOl3fErWV4zbkDjH3PXB56/Wf+CNEtCWeVSL9wXq9zJnlQuLu7FopubZB94svzQHBAsrEWp4F3y6SaI51cxbi+rlbMekjuZM186mLIuEW0KY0+A8LDHMNO8jdYnkHewepDSbKsMdwbiwHcZBWJz/ptY=,iv:pLO6YQOwOAu4MlPa/5x1N49lz4rCBl+DBb1T7cBFq8A=,tag:Y2GlB99wumdoSymTbrhupQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
