apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tlOY/9RC/+6jbVSCoOPUzPv5xMEvfSdymM4X3q4GCFrWvckhTBM4gw==,iv:CC0pKGqThfZu7wSZFjfdPC2vnSdVvVY9wt1nOqL100g=,tag:h7g4y4KxB0t1JSxQPE9A0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycHE2ZEUwWDNyazVNNHA2
            TkduckVoem5vUjRWazdVU1RsVzc1L3hDTFcwCkk5VFk4MUZLaUltSHJiY1hUamZH
            aGdYOU9DNThTNXIzUzlscTYzZVBaRHcKLS0tIEs1QjV6Qmk4dThzVjY5WFpsWXYx
            RUtwbW92djFMVFdxd3MwQW1NdHlYaVkKt4GffXSGeWPseF0Uy7kQT2k1kdZ8p1wB
            rX7wWpUuJW3Z+mvxlMgczeAFZZq92NDMJeWKk36Sfv00oI6izxjS2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T15:41:39Z"
    mac: ENC[AES256_GCM,data:HL/36EFZVy5qzGfBzSOSRs5nGlmvy0MD/jHE/xNqQDn8i5HQhjRDhvPAqm3EbtWdUMbjPMCgruH0Osd525ebLEi7JSjVFH8KlAtxXYUnkKtUJYIwquQHm/lbtP7Bl0v2Tc1sV6CbOdCkecwVsW/aIjX/e2RTaeUv6D0c5lKKWOQ=,iv:EDTOO4kffuKkJk28Ut97d2PZyktbL4gpfvslKSxp4Wo=,tag:9HRUHxHujiLG2ptdQclOnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
