apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Dhaw+dug6CjuPFQoaneCiABfbJzjKBE/Gztu0lvIe8HY50PcvvYs3g==,iv:Yk9syEUGbIMJWfdFB9g/toaWvpLWgF/cd/hrH+5mCDo=,tag:7aL+WDrcz35XSrezVpZDWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZzNxSEFGeHZ1RGQxNkcx
            VVlhcEhzVTkwbzJTcW1jcTZyam81Z2tTN2xvCmhvMDJoWUh6aHNGc2JQSFZscVNy
            ZnJ2U2lLNVYvd0NBSTdLOWpOM1dCQ3MKLS0tIFpDYXNtWWwxbVYyS1I3UncySkVx
            aEhvZmJyTVhsamp0YTNmeWVQZS9xeWMKfRu+P+hYtcZIDLeIc3ysDryiz5rw9Znu
            afL1FXLybIt2ElCNCxiPueAOyQMEl6CliZlBzEV6G//lGeqYjZAeHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T19:22:42Z"
    mac: ENC[AES256_GCM,data:gZG2F+Qokki+1XlpPAo9d4ldr+aluo1QR1Dnqq0zCND9nlzm183IHgvXKySvjFASUQ8JYoYtdXUqwcxbaQPjeIWnuQL9VuZEr+cZkNciximrQY3B0zYbBk8y2QJrolnpTGlwpXFQvGz/C9KkE32uDHCRHTH36mK7GJkb0IKE83Q=,iv:rh/unvxEzhbfeVt9osDDMwRfKk1zBxjk0xVFItWEBA4=,tag:jAIEiiFbhbdSy+6GYWq4Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
