apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:rzl93pOfNCpOhkjaoi+HAQD876zYnQeBgETlnkdvf1Jx60hiQat4Tw==,iv:0Gy+Ks8FXDPDWPFd3nLAaSL6dgB+xm1j98k4qWt+R/M=,tag:kQnA6y2Gs+IPXmhdG5uxhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIemhUQ3MwYndlWkZmTFJX
            dmIzQWxuRWVHekJGY1pHYVNISU1BdkFnY3dVCm1hbmNpbkZsejdUZGxYK2hkMHRE
            anl4bFJnK3duak5KcjEyT0gxc1htblkKLS0tIHNjMjMxMGgwTnlKUU10ZVhMTmc1
            Q1pyV3E1S0VHRW05cnRLZEROMDlpU00KTyJvwt/6HW9ZLqMx0yJEIh87wT1iZWbH
            RQGvHIBGE2ospyqxwsYpmExWKopR9UUF15AsabUexODvknOhZsnK2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T22:28:37Z"
    mac: ENC[AES256_GCM,data:ACIaes/iFeRUkx3hlVxFITfHPhBN2yzS1xRBZVPzMBRYN/z7Fflba56XXs0yh4+5dS9H26LDkn0LftjRaO+0HxrqImKEXTLpFYFqEgufWuEaR3TuWEWqVZSMOrTA1VAQ63WFsevJ2BhGhRa2W7iQprVbYB+nf8o3optabUQeLAo=,iv:j7DhuRBgacCo5U1iFjbNg9xOYGWZ9kLdjctNcG/M5CQ=,tag:YGwThluW7a+FRmns4akHzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
