apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:MEo9uHFddo5Q6zRZYBOoAWCkBhYMN+vEJYwh6rdN1Wkq0qIoVlurDQ==,iv:aeyIJRrZyBNzlQlkPwXF2td78CfbxwjgqgQ/No1vcPE=,tag:4La82t7AF+36WTPimacf2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V0pjRUJGdzI4NUVWbDBP
            UWYrVDJjV0VjWitHcUhVOGZqQXZidnlxdXdjCng3NGUyWDcxdm5Lbmo2Y2tZeGt6
            Q2JQbE4xQWlMa0l2UjJNbWJtUG9nNEkKLS0tIEloc1hIVzZ5N01nTDBpaFM3MC9K
            cm9LRFlmd1pIRWh1TWU4c05ubEtwNWcKn2BXKWORlAjhnTmMkkgvDZMJfCZwQryb
            RXsOyLo8wysRbZx4NMdXCP3FS07kvwA+NOx1K/xzZ4OostAWs1QbDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T19:03:20Z"
    mac: ENC[AES256_GCM,data:fTz3wSBV0MmeqEXZUXa6FRwfoL5Bi9ANf5Op6fWHD4RJJl+SM59Yel/wWfkAhzbDF8x1v4CgGoCUrXC5RT5qwLN0Sa+u574R4Xe5+oQ80IAo+8EQOP2GGGeKHWEAjy2LjNT1MzQWfxiIOv4RZHSBk5+nHzcyYEaQXI/kfqbtl0g=,iv:rLKsEltJWWv6qs8zAQLqZBg46tWCna7RazsabPPRD8o=,tag:ieD5SVFTFZfmu42VTtpKRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
