apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:PtW+1Hmmgrq7cYh4mCFx4sQgXr/WDmzsit99avG8AiQd0M2lmnMgUw==,iv:3eghJIwXwJlw5E3IHMTMmHDZLAIWoLW/zsmg1adOFn8=,tag:EQbu/29mSmChIhpApQTRWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdFZ0RXFYZ0tDVzJuREVV
            bDJOeWp5L2pIOGk1UEU3Y3pnRER4clRPYVQ0CjNUUG1mcDZGK1hEbTZrREZEQzNp
            WWR1dmI0eEYwUHp1bG01SURQZ0sremcKLS0tIGkzdW5XRnBiQVlnODNmZUJ5SG0y
            bDBhTjRZSDdqSm9yak9PVXJkbXBDamMKoIiZaAGZinv7s7sgKilU/dc2efmR+qCM
            NdlZ9GfVaK1gsl3c40DzOXHb0F96aw+/aVXC9OpTjazneYhv5COcYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T18:05:04Z"
    mac: ENC[AES256_GCM,data:i60xvl1o06UgOt/VYSHXBhU+wp9nhGDRDU7SARzvOtiajhO8wlXG/JLReNs1nXmFAZXaA9AFPX8CLX6ebgUE9JMMSbLdTSBUdqnq9eMK2AIw63fk1ASugp4t9XSc9Ax9FPZK4glVL/mYtEIA+8QcPj31/H1PzmPa9oIcff9K7No=,iv:tNGDcykBYUQJBzOJgMsUorFwDXkztglpu9R52CWE0J4=,tag:4V134OVDQ02GV0YU/ipoMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
