apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:k1kvvmmwh/Jb0xafrG2lv7Lm3/TjG4WWymdalXn5HvYaWK6oeXvATw==,iv:pL3Go+kynJXCwwVyl5d5KirEiBD5FcXb7n0wZaRdv0o=,tag:+lIcPF4vglclNlag0Sb+Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clq05mzytspfnjga3rwgajltyemkd4h5cdfnxx07y5h6w3zcuczstupc6a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbjYzSVZaWU4wcEpEUHVy
            UDNla2tvLzdWSmhyeENaT1lZYkZUd2FseEVnClhWdVd0cUFYNEZvZnpWN1k0anZi
            c3A4eUo1SFI4L2hrS3JrdjRxbEhUZkUKLS0tIEFFTG5OaXRPa1RLZEUrVmYySmJj
            RzRnbGdZbExvZDNEb1gwQVVqcklOTDQKUiuSwbdD51HsOyxKCaZQD9eK5l30kd9S
            GUFfHvwA2MpUhrxL2PAbRKthktXX8DUzr7E8msAeb5IV96h7oPhvdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-29T16:43:47Z"
    mac: ENC[AES256_GCM,data:HDwhtu4MUeB5Hvd3fSZhuE1OtqlyL5NrYV3p31T4Z0D/zEYbMPtvifma/vnR91IV6yKrIT41aUGElby+8mSBOeoEFWGtGkM/Caa0+JqM7UIctxQRD+LeloXvAEi0O9vGqPis42uex5blkUcRJ9pzbtJ44ypabSF1rJzEa9zNmxY=,iv:4deKLmhXuMKfhx+gLHx52qtNmEgiJ5TR8fgqrQou74A=,tag:RiOrEWY00GVNmbi84i5RGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
